2.02.150-1ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/clvm.init b/debian/clvm.init
--- a/debian/clvm.init
+++ b/debian/clvm.init
@@ -4,8 +4,8 @@
 # Provides:          clvm
 # Required-Start:    lvm2
 # Required-Stop:     lvm2
-# Should-Start:      cman corosync openais
-# Should-Stop:       cman corosync openais
+# Should-Start:      corosync dlm
+# Should-Stop:       corosync dlm
 # Default-Start:     S
 # Default-Stop:      0 6
 # Short-Description: start and stop the lvm cluster locking daemon
@@ -32,8 +32,11 @@ if [ ! -f /etc/cluster/cluster.conf ]; then
 	exit 0
 fi
 
-if ! cman_tool status >/dev/null 2>&1; then
-	log_failure_msg "clvmd: cluster is not running. Aborting."
+# Since the cluster service is not available, check the corosync
+# service is up and running. The corosync service is used in
+# conjunction with dlm to coordinate locking in clvm
+if ! /usr/sbin/corosync-quorumtool -s >/dev/null 2>&1; then
+	log_failure_msg "clvmd: corosync is not running. Aborting."
 	exit 0
 fi
 
@@ -46,6 +49,9 @@ DAEMON_OPTS="-T$CLVMDTIMEOUT"
 
 do_start()
 {
+	if [ ! -d "/run/lvm" ]; then
+        	mkdir /run/lvm
+	fi
 	start-stop-daemon --start --quiet --exec $DAEMON -- $DAEMON_OPTS || status="$?"
 	# flush cache
 	vgscan > /dev/null 2>&1 
@@ -131,6 +137,7 @@ case "$1" in
 			log_action_msg "$DESC is running" 
 		else
 			log_action_msg "$DESC is not running"
+			exit 3
 		fi
 		exit 0
 	;;
