2.02.104-1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/scripts/blkdeactivate.sh.in b/scripts/blkdeactivate.sh.in
--- a/scripts/blkdeactivate.sh.in
+++ b/scripts/blkdeactivate.sh.in
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2012 Red Hat, Inc. All rights reserved.
+# Copyright (C) 2012-2013 Red Hat, Inc. All rights reserved.
 #
 # This file is part of LVM2.
 #
@@ -36,9 +36,25 @@ UMOUNT="/bin/umount"
 DMSETUP="@sbindir@/dmsetup"
 LVM="@sbindir@/lvm"
 
+if $UMOUNT --help | grep -- "--all-targets" >$DEV_DIR/null; then
+	UMOUNT_OPTS="--all-targets "
+else
+	UMOUNT_OPTS=""
+	FINDMNT="/bin/findmnt -r --noheadings -u -o TARGET"
+	FINDMNT_READ="read -r mnt"
+fi
+DMSETUP_OPTS=""
+LVM_OPTS=""
+
 LSBLK="/bin/lsblk -r --noheadings -o TYPE,KNAME,NAME,MOUNTPOINT"
 LSBLK_VARS="local devtype local kname local name local mnt"
 LSBLK_READ="read -r devtype kname name mnt"
+SORT_MNT="/bin/sort -r -u -k 4"
+
+# Do not show tool errors by default (only done/skipping summary
+# message provided by this script) and no verbose mode by default.
+ERRORS=0
+VERBOSE=0
 
 # Do not unmount mounted devices by default.
 DO_UMOUNT=0
@@ -71,6 +87,7 @@ declare -A SKIP_VG_LIST=()
 declare -A SKIP_UMOUNT_LIST=(["/"]=1 ["/boot"]=1 \
                              ["/lib"]=1 ["/lib64"]=1 \
                              ["/bin"]=1 ["/sbin"]=1 \
+                             ["/var"]=1 ["/var/log"]=1 \
                              ["/usr"]=1 \
                              ["/usr/lib"]=1 ["/usr/lib64"]=1 \
                              ["/usr/sbin"]=1 ["/usr/bin"]=1)
@@ -86,10 +103,12 @@ usage() {
 	echo "      If devices are specified, deactivate only supplied devices and their holders."
 	echo
 	echo "  Options:"
+	echo "    -e | --errors                Show errors reported from tools"
 	echo "    -h | --help                  Show this help message"
 	echo "    -d | --dmoption  DM_OPTIONS  Comma separated DM specific options"
 	echo "    -l | --lvmoption LVM_OPTIONS Comma separated LVM specific options"
 	echo "    -u | --umount                Unmount the device if mounted"
+	echo "    -v | --verbose               Verbose mode (also implies -e)"
 	echo
 	echo "  Device specific options:"
 	echo "    DM_OPTIONS:"
@@ -119,16 +138,37 @@ is_top_level_device() {
 	test -z "$files"
 }
 
-device_umount () {
-	test -z "$mnt" && return 0;
+device_umount_one() {
+	test -z "$mnt" && return 0
 
 	if test -z "${SKIP_UMOUNT_LIST["$mnt"]}" -a "$DO_UMOUNT" -eq "1"; then
-		echo "  UMOUNT: unmounting $name ($kname) mounted on $mnt"
-		$UMOUNT "$mnt" || add_device_to_skip_list
+		echo -n "  [UMOUNT]: unmounting $name ($kname) mounted on $mnt... "
+		if eval $UMOUNT $UMOUNT_OPTS "$(printf $mnt)" $OUT $ERR; then
+			echo "done"
+		else
+			echo "skipping"
+			add_device_to_skip_list
+		fi
 	else
 		echo "  [SKIP]: unmount of $name ($kname) mounted on $mnt"
 		add_device_to_skip_list
 	fi
+}
+
+device_umount() {
+	test "$devtype" != "lvm" && test "${kname:0:3}" != "dm-" && return 0
+
+	# FINDMNT is defined only if umount --all-targets is not available.
+	# In that case, read the list of multiple mount points of one device
+	# using FINDMNT and unmount it one by one manually.
+	if test -z "$FINDMNT"; then
+		device_umount_one
+	else
+		while $FINDMNT_READ; do
+			device_umount_one || return 1
+		done <<< "`$FINDMNT $DEV_DIR/$kname`"
+	fi
+
 }
 
 deactivate_holders () {
@@ -141,9 +181,6 @@ deactivate_holders () {
 		test -e $SYS_BLK_DIR/$kname || continue
 		# check if the device not on the skip list already
 		test -z ${SKIP_DEVICE_LIST["$kname"]} || return 1
-
-		# try to unmount it if mounted
-		device_umount || return 1
 
 		# try to deactivate the holder
 		test $skip -eq 1 && skip=0 && continue
@@ -158,44 +195,56 @@ deactivate_dm () {
 
 	deactivate_holders "$DEV_DIR/mapper/$name" || return 1
 
-	echo "  DM: deactivating $devtype device $name ($kname)"
-	$DMSETUP $DMSETUP_OPTS remove "$name" || add_device_to_skip_list
+	echo -n "  [DM]: deactivating $devtype device $name ($kname)... "
+	if eval $DMSETUP $DMSETUP_OPTS remove "$name" $OUT $ERR; then
+		echo "done"
+	else
+		echo "skipping"
+		add_device_to_skip_list
+	fi
 }
 
 deactivate_lvm () {
 	local DM_VG_NAME; local DM_LV_NAME; local DM_LV_LAYER
 
-	eval $($DMSETUP splitname --nameprefixes --noheadings --rows "$name" LVM)
+	eval $(eval $DMSETUP splitname --nameprefixes --noheadings --rows "$name" LVM $ERR)
 	test -b "$DEV_DIR/$DM_VG_NAME/$DM_LV_NAME" || return 0
 	test -z ${SKIP_VG_LIST["$DM_VG_NAME"]} || return 1
 
-	# Deactivating only the LV specified
-	test $LVM_DO_WHOLE_VG -eq 0 && {
+	if test $LVM_DO_WHOLE_VG -eq 0; then
+		# Deactivating only the LV specified
 		deactivate_holders "$DEV_DIR/$DM_VG_NAME/$DM_LV_NAME" || {
 			add_device_to_skip_list
 			return 1
 		}
 
-		echo "  LVM: deactivating Logical Volume $DM_VG_NAME/$DM_LV_NAME"
-		$LVM lvchange --config "log{prefix=\"\"} $LVM_CONFIG" -aln $DM_VG_NAME/$DM_LV_NAME || {
+		echo -n "  [LVM]: deactivating Logical Volume $DM_VG_NAME/$DM_LV_NAME... "
+		if eval $LVM lvchange $LVM_OPTS --config \'log{prefix=\"\"} $LVM_CONFIG\' -aln $DM_VG_NAME/$DM_LV_NAME $OUT $ERR; then
+			echo "done"
+		else
+			echo "skipping"
 			add_device_to_skip_list
-			return 1
-		}
-		return 0
-	}
+		fi
 
-	# Deactivating the whole VG the LV is part of
-	lv_list=$($LVM vgs --config "$LVM_CONFIG" --noheadings --rows -o lv_name $DM_VG_NAME)
-	for lv in $lv_list; do
-		test -b "$DEV_DIR/$DM_VG_NAME/$lv" || continue
-		deactivate_holders "$DEV_DIR/$DM_VG_NAME/$lv" || {
+	else
+		# Deactivating the whole VG the LV is part of
+		lv_list=$(eval $LVM vgs --config "$LVM_CONFIG" --noheadings --rows -o lv_name $DM_VG_NAME $ERR)
+		for lv in $lv_list; do
+			test -b "$DEV_DIR/$DM_VG_NAME/$lv" || continue
+			deactivate_holders "$DEV_DIR/$DM_VG_NAME/$lv" || {
+				add_vg_to_skip_list
+				return 1
+			}
+		done
+
+		echo -n "  [LVM]: deactivating Volume Group $DM_VG_NAME... "
+		if eval $LVM vgchange $LVM_OPTS --config \'log{prefix=\"    \"} $LVM_CONFIG\' -aln $DM_VG_NAME $OUT $ERR; then
+			echo "done"
+		else
+			echo "skipping"
 			add_vg_to_skip_list
-			return 1
-		}
-	done
-
-	echo "  LVM: deactivating Volume Group $DM_VG_NAME"
-	$LVM vgchange --config "log{prefix=\"    \"} $LVM_CONFIG" -aln $DM_VG_NAME || add_vg_to_skip_list
+		fi
+	fi
 }
 
 deactivate () {
@@ -226,7 +275,16 @@ deactivate_all() {
 	echo "Deactivating block devices:"
 
 	if test $# -eq 0; then
-		# Deactivate all devices
+		#######################
+		# Process all devices #
+		#######################
+
+		# Unmount all relevant mountpoints first
+		while $LSBLK_READ; do
+			device_umount
+		done <<< "`$LSBLK | $SORT_MNT`"
+
+		# Do deactivate
 		while $LSBLK_READ; do
 			# 'disk' is at the bottom already and it's a real device
 			test "$devtype" = "disk" && continue
@@ -249,14 +307,26 @@ deactivate_all() {
 			deactivate || skip=1
 		done <<< "`$LSBLK -s`"
 	else
-		# Deactivate only specified devices
+		##################################
+		# Process only specified devices #
+		##################################
+
 		while test $# -ne 0; do
+			# Unmount all relevant mountpoints first
+			while $LSBLK_READ; do
+				device_umount
+			done <<< "`$LSBLK $1 | $SORT_MNT`"
+
+			# Do deactivate
 			# Single dm device tree deactivation.
 			if test -b "$1"; then
 				$LSBLK_READ <<< "`$LSBLK --nodeps $1`"
 
 				# check if the device is not on the skip list already
-				test -z ${SKIP_DEVICE_LIST["$kname"]} || continue
+				test -z ${SKIP_DEVICE_LIST["$kname"]} || {
+					shift
+					continue
+				}
 
 				deactivate
 			else
@@ -298,16 +368,37 @@ get_lvmopts() {
 	IFS=$ORIG_IFS
 }
 
+set_env() {
+	if test "$ERRORS" -eq "1"; then
+		unset ERR
+	else
+		ERR="2>$DEV_DIR/null"
+	fi
+
+	if test "$VERBOSE" -eq "1"; then
+		unset OUT
+		UMOUNT_OPTS+="-v"
+		DMSETUP_OPTS+="-vvvv"
+		LVM_OPTS+="-vvvv"
+	else
+		OUT="1>$DEV_DIR/null"
+	fi
+}
+
 while test $# -ne 0; do
 	case "$1" in
 		"") ;;
+		"-e"|"--errors") ERRORS=1 ;;
 		"-h"|"--help") usage ;;
 		"-d"|"--dmoption ") get_dmopts "$2" ; shift ;;
 		"-l"|"--lvmoption ") get_lvmopts "$2" ; shift ;;
 		"-u"|"--umount") DO_UMOUNT=1 ;;
+		"-v"|"--verbose") VERBOSE=1 ; ERRORS=1 ;;
+		"-vv") VERBOSE=1 ; ERRORS=1 ; set -x ;;
 		*) break ;;
 	esac
 	shift
 done
 
+set_env
 deactivate_all "$@"
